### ISSUE TITLE
Add pop2010 to LB neighborhood table

### ISSUE THREAD

**Issue by uclamapshare** [IDREsandbox/mdbla#5]
[https://mdbla.carto.com/dataset/lbpd_neighborhoods_join_1_10_17](https://mdbla.carto.com/dataset/lbpd_neighborhoods_join_1_10_17)

**Comment by albertkun** [comment]
Finished and joined pop2010 here:

https://mdbla.carto.com/dataset/lbpd_neighborhoods_join_1_10_17

The following postgresql was used:
```
update
lbpd_neighborhoods_join_1_10_17
set pop2010 = lasd_2010_2015_by_neighborhoods_mergev2.pop2010
from lasd_2010_2015_by_neighborhoods_mergev2
where lbpd_neighborhoods_join_1_10_17.slug = lasd_2010_2015_by_neighborhoods_mergev2.slug
```
